#!/usr/bin/env python3
"""
Phase 4 — sub-category 4d: Cayley graphs of larger groups.

Phase 1 tried A_5, S_5, S_4, D_n. Extend to:
  - PSL(2, q) for q ∈ {5, 7, 8, 9, 11, 13}
  - Mathieu groups (skip — they are huge; M_11 has order 7920)
  - Janko J_1 (order 175560) — skip
  - Suzuki/Sz(q) — skip

For each group G, generate via sympy's PermutationGroup and try several TF
generating sets (small Δ).

For TF: a Cayley graph Cay(G, S) is TF iff for every s,t ∈ S, st^{-1} ∉ S
and (st)^2 ≠ 1 doesn't create triangles. More concretely we just enumerate
edges and check TF after construction.
"""

from __future__ import annotations

import itertools
import os
import random
import sys
from fractions import Fraction

import networkx as nx

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (
    CLEBSCH_RATIO,
    is_triangle_free,
    girth,
    count_induced_5cycles,
    graph_stats,
    ratio_str,
    vs_clebsch,
    open_tsv,
    tsv_row,
)


# ============================================================ Group construction


def cayley_graph(elements, identity, op, inv, generators) -> nx.Graph:
    """
    Build Cay(G, S) where:
      elements: iterable of group elements (orbit-closed under multiplication).
      identity: identity element.
      op: function (g, h) -> g * h.
      inv: function (g) -> g^{-1}.
      generators: list of elements; if a generator s has s != s^{-1}, the
        edge set will include both directions automatically.

    Vertices = elements (mapped to 0..|G|-1). Edges = {(g, s*g) : g ∈ G,
    s ∈ S} — undirected, so it must be the case that S = S^{-1} for
    the graph to be undirected without loss.
    """
    # Ensure S is closed under inversion:
    S = list(generators)
    Si = [inv(s) for s in S]
    S_all = list({_canon_key(s) for s in S + Si})
    # rebuild list of actual elements (not just keys) from a dict keyed by canon.
    seen = {}
    for s in S + Si:
        seen[_canon_key(s)] = s
    S_full = list(seen.values())
    # Triangle-free: no s, t in S_full with s*t in S_full.
    if not _tf_check(S_full, op, identity):
        return None
    # Edge enumeration:
    idx = {_canon_key(g): i for i, g in enumerate(elements)}
    G = nx.Graph()
    G.add_nodes_from(range(len(elements)))
    for g in elements:
        ig = idx[_canon_key(g)]
        for s in S_full:
            sg = op(s, g)
            isg = idx.get(_canon_key(sg))
            if isg is not None and isg != ig:
                G.add_edge(ig, isg)
    return G


def _canon_key(g):
    """Hashable canonical key for a group element. Handles sympy Permutation
    via tuple-of-array_form; handles tuples directly; falls back to repr."""
    try:
        return tuple(g.array_form)
    except AttributeError:
        try:
            return tuple(g)
        except TypeError:
            return repr(g)


def _tf_check(S, op, identity) -> bool:
    """Triangle-free: no s, t ∈ S with op(s, t) ∈ S, where s,t,st all distinct
    and != identity."""
    Sset = {_canon_key(s): s for s in S}
    for s in S:
        if _canon_key(s) == _canon_key(identity):
            continue
        for t in S:
            if _canon_key(t) == _canon_key(identity):
                continue
            if _canon_key(s) == _canon_key(t):
                continue
            st = op(s, t)
            if _canon_key(st) in Sset:
                # Triangle: identity -> s -> s*t -> identity? Cayley graph
                # edges are {g, sg}; the triangle is {e, s, s*t} iff all
                # three of s, t, s*t (well, t = s^{-1}*(s*t)) are in S.
                # Since S is closed under inversion and S = S^{-1}, having
                # any 3-element multiplicative closure means a triangle.
                if _canon_key(st) != _canon_key(identity):
                    return False
    return True


# ============================================================ Groups via sympy


def psl_2_q(q: int):
    """Return (elements, identity, op, inv) for PSL(2, q) acting on PG(1, q).
    PSL(2,q) ⊂ Sym(q+1) via Möbius action. Use sympy.combinatorics."""
    from sympy.combinatorics import PermutationGroup, Permutation

    # PG(1, q) = {0, 1, ..., q-1, ∞} -> labels 0..q.
    # Generators (for q prime; q=8,9 need GF):
    if q in [5, 7, 11, 13]:
        # PSL(2, q) generated by (x -> x+1) and (x -> -1/x).
        def shift(x):
            if x == q:
                return q  # ∞ -> ∞
            return (x + 1) % q

        def invert(x):
            if x == q:
                return 0  # ∞ -> 0
            if x == 0:
                return q  # 0 -> ∞
            return (-pow(x, -1, q)) % q
        labels = list(range(q + 1))
    elif q == 8:
        import galois
        F = galois.GF(8)
        elems = [F(i) for i in range(8)]
        # labels: 0..7 = F(0..7), 8 = ∞
        labels = list(range(9))

        def to_F(x):
            return F(x) if x < 8 else None

        def shift(x):
            if x == 8:
                return 8
            return int(F(x) + F(1))

        def invert(x):
            if x == 8:
                return 0
            if x == 0:
                return 8
            return int(-F(x) ** -1)
    elif q == 9:
        import galois
        F = galois.GF(9)
        labels = list(range(10))

        def shift(x):
            if x == 9:
                return 9
            return int(F(x) + F(1))

        def invert(x):
            if x == 9:
                return 0
            if x == 0:
                return 9
            return int(-F(x) ** -1)
    else:
        raise NotImplementedError(f"PSL(2,{q}) not built")

    n = q + 1
    g1 = Permutation([shift(x) for x in labels])
    g2 = Permutation([invert(x) for x in labels])
    GG = PermutationGroup([g1, g2])
    elements = list(GG.generate())
    identity = Permutation(list(range(n)))
    op = lambda a, b: a * b
    inv = lambda a: a ** -1
    return elements, identity, op, inv


def s_n(n: int):
    from sympy.combinatorics import PermutationGroup, Permutation
    if n < 2:
        return None
    # S_n generated by transposition (0,1) and cycle (0,1,...,n-1).
    cyc = list(range(1, n)) + [0]
    g_cycle = Permutation(cyc)
    g_transp = Permutation(0, 1, size=n)
    GG = PermutationGroup([g_cycle, g_transp])
    elements = list(GG.generate())
    identity = Permutation(list(range(n)))
    op = lambda a, b: a * b
    inv = lambda a: a ** -1
    return elements, identity, op, inv


def a_n(n: int):
    from sympy.combinatorics import PermutationGroup, Permutation
    if n < 3:
        return None
    g1 = Permutation([1, 2, 0] + list(range(3, n)))  # 3-cycle (0,1,2)
    if n >= 5:
        # alt: another 3-cycle to span A_n
        g2 = Permutation([0, 2, 3, 4, 1] + list(range(5, n)))  # (1,2,3,4) — wait that's a 4-cycle
        # use (n-3, n-2, n-1) for odd n, etc. Sympy can compute A_n directly.
        from sympy.combinatorics.named_groups import AlternatingGroup
        GG = AlternatingGroup(n)
    else:
        GG = PermutationGroup([g1])
    elements = list(GG.generate())
    identity = Permutation(list(range(n)))
    op = lambda a, b: a * b
    inv = lambda a: a ** -1
    return elements, identity, op, inv


def random_tf_generators(elements, identity, op, inv, target_deg: int,
                          max_tries: int = 80) -> list | None:
    """Sample a random TF generating multiset of size target_deg/2 (un-inverted
    generators). Reject if it creates a triangle in Cay(G, S∪S^{-1}).
    Returns the un-inverted list S; the actual graph has degree =
    |S ∪ S^{-1}|, which is target_deg iff every s satisfies s != s^{-1}.
    """
    # Build map from key -> element for fast inversion check.
    half = target_deg // 2
    non_idents = [g for g in elements if _canon_key(g) != _canon_key(identity)]
    for tries in range(max_tries):
        S = random.sample(non_idents, half)
        # Try TF check.
        full = list(S)
        for s in S:
            full.append(inv(s))
        # Dedupe by canonical key.
        seen = {}
        for f in full:
            seen[_canon_key(f)] = f
        full = list(seen.values())
        # Degree = len(full).
        if _tf_check(full, op, identity):
            return full
    return None


# ============================================================ Driver


def run(tsv_path: str, samples_per_group: int = 5):
    f = open_tsv(tsv_path, append=True)
    results = []

    # NOTE: PSL(2, q) for prime-power q (q ∈ {8, 9}) is NOT correctly
    # constructed by my generator pair x->x+1, x->-1/x because in
    # characteristic 2 the additive shift has order 2. Restrict to
    # prime q here; prime-power PSL extension is a stretch goal.
    group_specs = [
        ("PSL(2,5)", lambda: psl_2_q(5), [4, 6]),
        ("PSL(2,7)", lambda: psl_2_q(7), [4, 6, 8]),
        ("PSL(2,11)", lambda: psl_2_q(11), [4, 6]),
        ("PSL(2,13)", lambda: psl_2_q(13), [4, 6]),
        # extend Phase 1 small-symmetric coverage:
        ("S_6", lambda: s_n(6), [4, 6, 8]),
        ("S_7", lambda: s_n(7), [4, 6]),
        ("A_6", lambda: a_n(6), [4, 6]),
        ("A_7", lambda: a_n(7), [4, 6]),
    ]

    random.seed(20260521)

    for gname, gctor, degs in group_specs:
        try:
            elements, identity, op, inv = gctor()
        except Exception as e:
            print(f"[4d] {gname}: FAILED to construct ({e})")
            continue
        n_grp = len(elements)
        print(f"[4d] {gname}: |G|={n_grp}")
        for D_target in degs:
            best_r = Fraction(0)
            for s in range(samples_per_group):
                S_full = random_tf_generators(elements, identity, op, inv,
                                              D_target, max_tries=50)
                if S_full is None:
                    continue
                D_actual = len(S_full)
                G = cayley_graph(elements, identity, op, inv, S_full)
                if G is None:
                    continue
                tf, r, P = tsv_row(f, "4d_Cayley",
                                   f"{gname}_D{D_actual}_s{s}", G)
                if r > best_r:
                    best_r = r
                    if r > CLEBSCH_RATIO:
                        print(f"  [!!!] {gname} D={D_actual} s={s}: "
                              f"ratio={float(r):.6f} > Clebsch!")
            print(f"  D~{D_target}: best ratio = {float(best_r):.6f}")
            results.append((gname, D_target, best_r))
    f.close()

    if results:
        best = max(results, key=lambda t: t[2])
        print(f"\n4d SUMMARY: best ratio = {float(best[2]):.6f} at "
              f"{best[0]} D~{best[1]}")
    return results


if __name__ == "__main__":
    tsv = sys.argv[1] if len(sys.argv) > 1 else (
        os.path.join(os.path.dirname(__file__), "..", "phase4_logs", "all_graphs.tsv")
    )
    sps = int(sys.argv[2]) if len(sys.argv) > 2 else 3
    run(tsv, samples_per_group=sps)
